apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql
spec:
  releaseName: psql
  chart:
    spec:
      chart: nxs-universal-chart
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: nixys
      interval: 1m
  interval: 1m
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    force: false
  valuesFrom:
    - kind: ConfigMap
      name: "00-psql-helm-chart-default-values"
      valuesKey: values.yaml